// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
public class City {

    private java.lang.String _cityName;

    private Date _dateEstablished;

    private Point _cityCenter;

    private Point _centralStation;

    private long _numOfResidents;

    private int _numOfNeighborhoods;

    private final int MIN_RESIDENTS = 0;

    private final int MIN_NEIGHBORHOODS = 1;

    public City(java.lang.String cityName, int dayEstablished, int monthEstablished, int yearEstablished, int centerX,
            int centerY, int stationX, int stationY, long numOfResidents, int noOfNeighborhoods) {
    }

    public City(City other) {
    }

    public java.lang.String getCityName() {
        return null;
    }

    public Date getDateEstablished() {
        return null;
    }

    public Point getCityCenter() {
        return null;
    }

    public Point getCentralStation() {
        return null;
    }

    public long getNumOfResidents() {
        return 0;
    }

    public int getNumOfNeighborhoods() {
        return 0;
    }

    public void setCityName(java.lang.String cityName) {
    }

    public void setDateEstablished(Date dateEst) {
    }

    public void setCityCenter(Point cityCenter) {
    }

    public void setCentralStation(Point centralStation) {
    }

    public void setNumOfResidents(long numOfResidents) {
    }

    public void setNumOfNeighborhoods(int noOfNeighborhoods) {
    }

    public java.lang.String toString() {
        return null;
    }

    public boolean equals(City other) {
        return false;
    }

    public boolean addResidents(long residentsUpdate) {
        return false;
    }

    public void moveCentralStation(int deltaX, int deltaY) {
    }

    public double distanceBetweenCenterAndStation() {
        return 0;
    }

    public City newCity(java.lang.String newCityName, int dX, int dY) {
        return null;
    }

    public boolean cityEstablishedBetweenDates(Date date1, Date date2) {
        return false;
    }

    public int establishmentDateDiff(City other) {
        return 0;
    }
}