// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
public class Date {

    private int _day;

    private int _month;

    private int _year;

    private final int DEFAULT_DAY = 1;

    private final int DEFAULT_MONTH = 1;

    private final int DEFAULT_YEAR = 2000;

    private final int JAN = 1;

    private final int FEB = 2;

    private final int MAR = 3;

    private final int APR = 4;

    private final int MAY = 5;

    private final int JUN = 6;

    private final int JUL = 7;

    private final int AUG = 8;

    private final int SEP = 9;

    private final int OCT = 10;

    private final int NOV = 11;

    private final int DEC = 12;

    private final int DAYS_IN_LEAP = 29;

    private final int DAYS_IN_NON_LEAP = 28;

    private final int MAX_DAYS_IN_MONTH = 31;

    public Date(int day, int month, int year) {
    }

    public Date(Date other) {
    }

    public int getYear() {
        return 0;
    }

    public int getMonth() {
        return 0;
    }

    public int getDay() {
        return 0;
    }

    public void setYear(int yearToSet) {
    }

    public void setMonth(int monthToSet) {
    }

    public void setDay(int dayToSet) {
    }

    public boolean equals(Date other) {
        return false;
    }

    public boolean before(Date other) {
        return false;
    }

    public boolean after(Date other) {
        return false;
    }

    public int difference(Date other) {
        return 0;
    }

    public java.lang.String toString() {
        return null;
    }

    public Date tomorrow() {
        return null;
    }

    private boolean isValid(int d, int m, int y) {
        return false;
    }

    private boolean dayInRange(int d) {
        return false;
    }

    private boolean monthInRange(int m) {
        return false;
    }

    private boolean yearInRange(int y) {
        return false;
    }

    private boolean leap(int y) {
        return false;
    }

    private int calculateDate(int day, int month, int year) {
        return 0;
    }
}