// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
public class Point {

    private int _x;

    private int _y;

    private final int MIN_COORDINATE = 0;

    public Point(int x, int y) {
    }

    public Point(Point other) {
    }

    public int getX() {
        return 0;
    }

    public int getY() {
        return 0;
    }

    public void setX(int num) {
    }

    public void setY(int num) {
    }

    public boolean equals(Point other) {
        return false;
    }

    public boolean isAbove(Point other) {
        return false;
    }

    public boolean isUnder(Point other) {
        return false;
    }

    public boolean isLeft(Point other) {
        return false;
    }

    public boolean isRight(Point other) {
        return false;
    }

    public double distance(Point p) {
        return 0;
    }

    public void move(int deltaX, int deltaY) {
    }

    public Point middle(Point p) {
        return null;
    }

    public java.lang.String toString() {
        return null;
    }
}